#!/usr/bin/env bash
# regen.sh — regenerate the Go bindings for the AUTHORED service proto.
#
# Scope: proto/*_service.proto ONLY. proto/rep.proto and proto/recover.proto
# share the directory but are the opposite kind of file — derived from the
# grammar, regenerated by `go run ./cmd/gluon genproto -out gen` and then
# re-prepending each banner (CLAUDE.md rule 6). This script must never touch
# them, which is what the explicit filename below guarantees.
#
# Sources live in proto/, generated Go in proto/pb/ (the layout xmile uses).
# The generated .pb.go files are COMMITTED, so an ordinary build needs no
# protoc; only editing the .proto does.
set -euo pipefail
cd "$(dirname "$0")"

for t in protoc protoc-gen-go protoc-gen-go-grpc; do
  command -v "$t" >/dev/null 2>&1 || {
    echo "[regen] FATAL: $t not found." >&2
    echo "  brew install protobuf" >&2
    echo "  go install google.golang.org/protobuf/cmd/protoc-gen-go@latest" >&2
    echo "  go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest" >&2
    exit 1
  }
done

echo "[regen] proto/robotstxt_service.proto"
mkdir -p proto/pb
protoc \
  --proto_path=proto \
  --go_out=proto/pb --go_opt=paths=source_relative \
  --go-grpc_out=proto/pb --go-grpc_opt=paths=source_relative \
  proto/robotstxt_service.proto

gofmt -w proto/pb
echo "[regen] OK — commit the regenerated .pb.go files"
