// robotstxt_service.proto — the gRPC surface of cmd/robotstxt-svc.
//
// AUTHORED, NOT GENERATED — the one hand-written proto in this repo.
//
// It shares this directory with rep.proto and recover.proto, which are the
// opposite: DERIVED FROM THE GRAMMAR by `gluon genproto` and regenerated, never
// hand-edited (CLAUDE.md rule 6). Nothing here is grammar-derived, and
// `gluon genproto` neither reads nor writes this file — the `_service` suffix
// is the marker for which kind a file is.
//
// Regenerate its Go bindings with ./regen.sh after editing.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.35.1
// source: robotstxt_service.proto

package robotstxtpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FetchOutcome is how a robots.txt fetch resolved, in RFC 9309 §2.3.1 terms.
type FetchOutcome int32

const (
	FetchOutcome_FETCH_OUTCOME_UNSPECIFIED FetchOutcome = 0
	// Rules were fetched and parsed (§2.3.1.1).
	FetchOutcome_FETCH_OUTCOME_SUCCESS FetchOutcome = 1
	// No valid robots.txt exists — 4xx other than 429, or a redirect chain that
	// never resolved. The crawler MAY access any resource (§2.3.1.3): allow all.
	FetchOutcome_FETCH_OUTCOME_UNAVAILABLE FetchOutcome = 2
	// robots.txt is undefined — 429, 5xx, DNS or network failure. The crawler
	// MUST assume complete disallow (§2.3.1.4).
	FetchOutcome_FETCH_OUTCOME_UNREACHABLE FetchOutcome = 3
)

// Enum value maps for FetchOutcome.
var (
	FetchOutcome_name = map[int32]string{
		0: "FETCH_OUTCOME_UNSPECIFIED",
		1: "FETCH_OUTCOME_SUCCESS",
		2: "FETCH_OUTCOME_UNAVAILABLE",
		3: "FETCH_OUTCOME_UNREACHABLE",
	}
	FetchOutcome_value = map[string]int32{
		"FETCH_OUTCOME_UNSPECIFIED": 0,
		"FETCH_OUTCOME_SUCCESS":     1,
		"FETCH_OUTCOME_UNAVAILABLE": 2,
		"FETCH_OUTCOME_UNREACHABLE": 3,
	}
)

func (x FetchOutcome) Enum() *FetchOutcome {
	p := new(FetchOutcome)
	*p = x
	return p
}

func (x FetchOutcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FetchOutcome) Descriptor() protoreflect.EnumDescriptor {
	return file_robotstxt_service_proto_enumTypes[0].Descriptor()
}

func (FetchOutcome) Type() protoreflect.EnumType {
	return &file_robotstxt_service_proto_enumTypes[0]
}

func (x FetchOutcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FetchOutcome.Descriptor instead.
func (FetchOutcome) EnumDescriptor() ([]byte, []int) {
	return file_robotstxt_service_proto_rawDescGZIP(), []int{0}
}

type ParseRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A bare host ("example.com"), an origin, or any URL — the origin is derived
	// from it. A missing scheme defaults to https.
	Domain string `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	// The product token whose group applies. Defaults to "*".
	Agent string `protobuf:"bytes,2,opt,name=agent,proto3" json:"agent,omitempty"`
	// Return the raw robots.txt, so a caller can pass it to Filter without a
	// second fetch.
	IncludeText   bool `protobuf:"varint,3,opt,name=include_text,json=includeText,proto3" json:"include_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseRequest) Reset() {
	*x = ParseRequest{}
	mi := &file_robotstxt_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseRequest) ProtoMessage() {}

func (x *ParseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_robotstxt_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseRequest.ProtoReflect.Descriptor instead.
func (*ParseRequest) Descriptor() ([]byte, []int) {
	return file_robotstxt_service_proto_rawDescGZIP(), []int{0}
}

func (x *ParseRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *ParseRequest) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *ParseRequest) GetIncludeText() bool {
	if x != nil {
		return x.IncludeText
	}
	return false
}

type ParseResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Origin     string                 `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
	RobotsUrl  string                 `protobuf:"bytes,2,opt,name=robots_url,json=robotsUrl,proto3" json:"robots_url,omitempty"`
	Outcome    FetchOutcome           `protobuf:"varint,3,opt,name=outcome,proto3,enum=robotstxt.svc.v1.FetchOutcome" json:"outcome,omitempty"`
	StatusCode int32                  `protobuf:"varint,4,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	FetchError string                 `protobuf:"bytes,5,opt,name=fetch_error,json=fetchError,proto3" json:"fetch_error,omitempty"`
	// Carry the §2.3.1 verdict when there are no rules to apply. Exactly one is
	// true unless outcome is SUCCESS.
	AllowAll    bool `protobuf:"varint,6,opt,name=allow_all,json=allowAll,proto3" json:"allow_all,omitempty"`
	DisallowAll bool `protobuf:"varint,7,opt,name=disallow_all,json=disallowAll,proto3" json:"disallow_all,omitempty"`
	// The Sitemap: lines, resolved against the origin. Document-global, not
	// group-scoped (RFC 9309 §2.2.4).
	Sitemaps []string `protobuf:"bytes,8,rep,name=sitemaps,proto3" json:"sitemaps,omitempty"`
	// The Crawl-delay of the group matching the agent, if any. Not part of
	// RFC 9309, and google's parser ignores it.
	CrawlDelaySeconds float64 `protobuf:"fixed64,9,opt,name=crawl_delay_seconds,json=crawlDelaySeconds,proto3" json:"crawl_delay_seconds,omitempty"`
	// Which parse tier produced the events: "strict" (the document satisfies the
	// RFC 9309 grammar) or "recovered" (per-line recovery).
	Tier string `protobuf:"bytes,10,opt,name=tier,proto3" json:"tier,omitempty"`
	// Lines no grammar rule matched, recovered by the robots.cc fallback.
	IrregularLines int32  `protobuf:"varint,11,opt,name=irregular_lines,json=irregularLines,proto3" json:"irregular_lines,omitempty"`
	RobotsTxt      string `protobuf:"bytes,12,opt,name=robots_txt,json=robotsTxt,proto3" json:"robots_txt,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ParseResponse) Reset() {
	*x = ParseResponse{}
	mi := &file_robotstxt_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseResponse) ProtoMessage() {}

func (x *ParseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_robotstxt_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseResponse.ProtoReflect.Descriptor instead.
func (*ParseResponse) Descriptor() ([]byte, []int) {
	return file_robotstxt_service_proto_rawDescGZIP(), []int{1}
}

func (x *ParseResponse) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *ParseResponse) GetRobotsUrl() string {
	if x != nil {
		return x.RobotsUrl
	}
	return ""
}

func (x *ParseResponse) GetOutcome() FetchOutcome {
	if x != nil {
		return x.Outcome
	}
	return FetchOutcome_FETCH_OUTCOME_UNSPECIFIED
}

func (x *ParseResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ParseResponse) GetFetchError() string {
	if x != nil {
		return x.FetchError
	}
	return ""
}

func (x *ParseResponse) GetAllowAll() bool {
	if x != nil {
		return x.AllowAll
	}
	return false
}

func (x *ParseResponse) GetDisallowAll() bool {
	if x != nil {
		return x.DisallowAll
	}
	return false
}

func (x *ParseResponse) GetSitemaps() []string {
	if x != nil {
		return x.Sitemaps
	}
	return nil
}

func (x *ParseResponse) GetCrawlDelaySeconds() float64 {
	if x != nil {
		return x.CrawlDelaySeconds
	}
	return 0
}

func (x *ParseResponse) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

func (x *ParseResponse) GetIrregularLines() int32 {
	if x != nil {
		return x.IrregularLines
	}
	return 0
}

func (x *ParseResponse) GetRobotsTxt() string {
	if x != nil {
		return x.RobotsTxt
	}
	return ""
}

type FilterRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RobotsTxt string                 `protobuf:"bytes,1,opt,name=robots_txt,json=robotsTxt,proto3" json:"robots_txt,omitempty"`
	Agent     string                 `protobuf:"bytes,2,opt,name=agent,proto3" json:"agent,omitempty"`
	Urls      []string               `protobuf:"bytes,3,rep,name=urls,proto3" json:"urls,omitempty"`
	// Short-circuit the matcher when the caller already holds a §2.3.1 verdict
	// from Parse and there are no rules to apply. Mutually exclusive.
	AllowAll      bool `protobuf:"varint,4,opt,name=allow_all,json=allowAll,proto3" json:"allow_all,omitempty"`
	DisallowAll   bool `protobuf:"varint,5,opt,name=disallow_all,json=disallowAll,proto3" json:"disallow_all,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterRequest) Reset() {
	*x = FilterRequest{}
	mi := &file_robotstxt_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterRequest) ProtoMessage() {}

func (x *FilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_robotstxt_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterRequest.ProtoReflect.Descriptor instead.
func (*FilterRequest) Descriptor() ([]byte, []int) {
	return file_robotstxt_service_proto_rawDescGZIP(), []int{2}
}

func (x *FilterRequest) GetRobotsTxt() string {
	if x != nil {
		return x.RobotsTxt
	}
	return ""
}

func (x *FilterRequest) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *FilterRequest) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

func (x *FilterRequest) GetAllowAll() bool {
	if x != nil {
		return x.AllowAll
	}
	return false
}

func (x *FilterRequest) GetDisallowAll() bool {
	if x != nil {
		return x.DisallowAll
	}
	return false
}

type FilterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       []string               `protobuf:"bytes,1,rep,name=allowed,proto3" json:"allowed,omitempty"`
	Disallowed    []string               `protobuf:"bytes,2,rep,name=disallowed,proto3" json:"disallowed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterResponse) Reset() {
	*x = FilterResponse{}
	mi := &file_robotstxt_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterResponse) ProtoMessage() {}

func (x *FilterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_robotstxt_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterResponse.ProtoReflect.Descriptor instead.
func (*FilterResponse) Descriptor() ([]byte, []int) {
	return file_robotstxt_service_proto_rawDescGZIP(), []int{3}
}

func (x *FilterResponse) GetAllowed() []string {
	if x != nil {
		return x.Allowed
	}
	return nil
}

func (x *FilterResponse) GetDisallowed() []string {
	if x != nil {
		return x.Disallowed
	}
	return nil
}

var File_robotstxt_service_proto protoreflect.FileDescriptor

const file_robotstxt_service_proto_rawDesc = "" +
	"\n" +
	"\x17robotstxt_service.proto\x12\x10robotstxt.svc.v1\"_\n" +
	"\fParseRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x14\n" +
	"\x05agent\x18\x02 \x01(\tR\x05agent\x12!\n" +
	"\finclude_text\x18\x03 \x01(\bR\vincludeText\"\xaa\x03\n" +
	"\rParseResponse\x12\x16\n" +
	"\x06origin\x18\x01 \x01(\tR\x06origin\x12\x1d\n" +
	"\n" +
	"robots_url\x18\x02 \x01(\tR\trobotsUrl\x128\n" +
	"\aoutcome\x18\x03 \x01(\x0e2\x1e.robotstxt.svc.v1.FetchOutcomeR\aoutcome\x12\x1f\n" +
	"\vstatus_code\x18\x04 \x01(\x05R\n" +
	"statusCode\x12\x1f\n" +
	"\vfetch_error\x18\x05 \x01(\tR\n" +
	"fetchError\x12\x1b\n" +
	"\tallow_all\x18\x06 \x01(\bR\ballowAll\x12!\n" +
	"\fdisallow_all\x18\a \x01(\bR\vdisallowAll\x12\x1a\n" +
	"\bsitemaps\x18\b \x03(\tR\bsitemaps\x12.\n" +
	"\x13crawl_delay_seconds\x18\t \x01(\x01R\x11crawlDelaySeconds\x12\x12\n" +
	"\x04tier\x18\n" +
	" \x01(\tR\x04tier\x12'\n" +
	"\x0firregular_lines\x18\v \x01(\x05R\x0eirregularLines\x12\x1d\n" +
	"\n" +
	"robots_txt\x18\f \x01(\tR\trobotsTxt\"\x98\x01\n" +
	"\rFilterRequest\x12\x1d\n" +
	"\n" +
	"robots_txt\x18\x01 \x01(\tR\trobotsTxt\x12\x14\n" +
	"\x05agent\x18\x02 \x01(\tR\x05agent\x12\x12\n" +
	"\x04urls\x18\x03 \x03(\tR\x04urls\x12\x1b\n" +
	"\tallow_all\x18\x04 \x01(\bR\ballowAll\x12!\n" +
	"\fdisallow_all\x18\x05 \x01(\bR\vdisallowAll\"J\n" +
	"\x0eFilterResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x03(\tR\aallowed\x12\x1e\n" +
	"\n" +
	"disallowed\x18\x02 \x03(\tR\n" +
	"disallowed*\x86\x01\n" +
	"\fFetchOutcome\x12\x1d\n" +
	"\x19FETCH_OUTCOME_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15FETCH_OUTCOME_SUCCESS\x10\x01\x12\x1d\n" +
	"\x19FETCH_OUTCOME_UNAVAILABLE\x10\x02\x12\x1d\n" +
	"\x19FETCH_OUTCOME_UNREACHABLE\x10\x032\xa6\x01\n" +
	"\rRobotsService\x12H\n" +
	"\x05Parse\x12\x1e.robotstxt.svc.v1.ParseRequest\x1a\x1f.robotstxt.svc.v1.ParseResponse\x12K\n" +
	"\x06Filter\x12\x1f.robotstxt.svc.v1.FilterRequest\x1a .robotstxt.svc.v1.FilterResponseB=Z;github.com/accretional/proto-robotstxt/proto/pb;robotstxtpbb\x06proto3"

var (
	file_robotstxt_service_proto_rawDescOnce sync.Once
	file_robotstxt_service_proto_rawDescData []byte
)

func file_robotstxt_service_proto_rawDescGZIP() []byte {
	file_robotstxt_service_proto_rawDescOnce.Do(func() {
		file_robotstxt_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_robotstxt_service_proto_rawDesc), len(file_robotstxt_service_proto_rawDesc)))
	})
	return file_robotstxt_service_proto_rawDescData
}

var file_robotstxt_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_robotstxt_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_robotstxt_service_proto_goTypes = []any{
	(FetchOutcome)(0),      // 0: robotstxt.svc.v1.FetchOutcome
	(*ParseRequest)(nil),   // 1: robotstxt.svc.v1.ParseRequest
	(*ParseResponse)(nil),  // 2: robotstxt.svc.v1.ParseResponse
	(*FilterRequest)(nil),  // 3: robotstxt.svc.v1.FilterRequest
	(*FilterResponse)(nil), // 4: robotstxt.svc.v1.FilterResponse
}
var file_robotstxt_service_proto_depIdxs = []int32{
	0, // 0: robotstxt.svc.v1.ParseResponse.outcome:type_name -> robotstxt.svc.v1.FetchOutcome
	1, // 1: robotstxt.svc.v1.RobotsService.Parse:input_type -> robotstxt.svc.v1.ParseRequest
	3, // 2: robotstxt.svc.v1.RobotsService.Filter:input_type -> robotstxt.svc.v1.FilterRequest
	2, // 3: robotstxt.svc.v1.RobotsService.Parse:output_type -> robotstxt.svc.v1.ParseResponse
	4, // 4: robotstxt.svc.v1.RobotsService.Filter:output_type -> robotstxt.svc.v1.FilterResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_robotstxt_service_proto_init() }
func file_robotstxt_service_proto_init() {
	if File_robotstxt_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_robotstxt_service_proto_rawDesc), len(file_robotstxt_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_robotstxt_service_proto_goTypes,
		DependencyIndexes: file_robotstxt_service_proto_depIdxs,
		EnumInfos:         file_robotstxt_service_proto_enumTypes,
		MessageInfos:      file_robotstxt_service_proto_msgTypes,
	}.Build()
	File_robotstxt_service_proto = out.File
	file_robotstxt_service_proto_goTypes = nil
	file_robotstxt_service_proto_depIdxs = nil
}
