// robotstxt_service.proto — the gRPC surface of cmd/robotstxt-svc.
//
// AUTHORED, NOT GENERATED — the one hand-written proto in this repo.
//
// It shares this directory with rep.proto and recover.proto, which are the
// opposite: DERIVED FROM THE GRAMMAR by `gluon genproto` and regenerated, never
// hand-edited (CLAUDE.md rule 6). Nothing here is grammar-derived, and
// `gluon genproto` neither reads nor writes this file — the `_service` suffix
// is the marker for which kind a file is.
//
// Regenerate its Go bindings with ./regen.sh after editing.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.35.1
// source: robotstxt_service.proto

package robotstxtpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RobotsService_Parse_FullMethodName  = "/robotstxt.svc.v1.RobotsService/Parse"
	RobotsService_Filter_FullMethodName = "/robotstxt.svc.v1.RobotsService/Filter"
)

// RobotsServiceClient is the client API for RobotsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RobotsService answers the two questions a crawler asks of a robots.txt.
type RobotsServiceClient interface {
	// Parse fetches a domain's robots.txt and reports what it says: the sitemaps
	// to walk, the crawl delay to pace by, and — when there are no rules to
	// apply — the RFC 9309 §2.3.1 verdict.
	Parse(ctx context.Context, in *ParseRequest, opts ...grpc.CallOption) (*ParseResponse, error)
	// Filter applies a robots.txt to a list of URLs. This is what turns "URLs a
	// sitemap lists" into "URLs this agent may fetch".
	Filter(ctx context.Context, in *FilterRequest, opts ...grpc.CallOption) (*FilterResponse, error)
}

type robotsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRobotsServiceClient(cc grpc.ClientConnInterface) RobotsServiceClient {
	return &robotsServiceClient{cc}
}

func (c *robotsServiceClient) Parse(ctx context.Context, in *ParseRequest, opts ...grpc.CallOption) (*ParseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParseResponse)
	err := c.cc.Invoke(ctx, RobotsService_Parse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *robotsServiceClient) Filter(ctx context.Context, in *FilterRequest, opts ...grpc.CallOption) (*FilterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FilterResponse)
	err := c.cc.Invoke(ctx, RobotsService_Filter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RobotsServiceServer is the server API for RobotsService service.
// All implementations must embed UnimplementedRobotsServiceServer
// for forward compatibility.
//
// RobotsService answers the two questions a crawler asks of a robots.txt.
type RobotsServiceServer interface {
	// Parse fetches a domain's robots.txt and reports what it says: the sitemaps
	// to walk, the crawl delay to pace by, and — when there are no rules to
	// apply — the RFC 9309 §2.3.1 verdict.
	Parse(context.Context, *ParseRequest) (*ParseResponse, error)
	// Filter applies a robots.txt to a list of URLs. This is what turns "URLs a
	// sitemap lists" into "URLs this agent may fetch".
	Filter(context.Context, *FilterRequest) (*FilterResponse, error)
	mustEmbedUnimplementedRobotsServiceServer()
}

// UnimplementedRobotsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRobotsServiceServer struct{}

func (UnimplementedRobotsServiceServer) Parse(context.Context, *ParseRequest) (*ParseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Parse not implemented")
}
func (UnimplementedRobotsServiceServer) Filter(context.Context, *FilterRequest) (*FilterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Filter not implemented")
}
func (UnimplementedRobotsServiceServer) mustEmbedUnimplementedRobotsServiceServer() {}
func (UnimplementedRobotsServiceServer) testEmbeddedByValue()                       {}

// UnsafeRobotsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RobotsServiceServer will
// result in compilation errors.
type UnsafeRobotsServiceServer interface {
	mustEmbedUnimplementedRobotsServiceServer()
}

func RegisterRobotsServiceServer(s grpc.ServiceRegistrar, srv RobotsServiceServer) {
	// If the following call panics, it indicates UnimplementedRobotsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RobotsService_ServiceDesc, srv)
}

func _RobotsService_Parse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RobotsServiceServer).Parse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RobotsService_Parse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RobotsServiceServer).Parse(ctx, req.(*ParseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RobotsService_Filter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RobotsServiceServer).Filter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RobotsService_Filter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RobotsServiceServer).Filter(ctx, req.(*FilterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RobotsService_ServiceDesc is the grpc.ServiceDesc for RobotsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RobotsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "robotstxt.svc.v1.RobotsService",
	HandlerType: (*RobotsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Parse",
			Handler:    _RobotsService_Parse_Handler,
		},
		{
			MethodName: "Filter",
			Handler:    _RobotsService_Filter_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "robotstxt_service.proto",
}
